Update Dockerfile to fix a few important typos
- doesn't override shell's PATH to be "." (which was breaking all commands)
- points to the correct location of the start.js file (src/start.js)
- corrects the suggested "To run" comment to have acebase instead of acebace (with a second 'c')

This dramatically improves the dockerfile's functionality, however it doesn't get the setup to a fully running state for me due to a TypeError at:
/app/node_modules/acebase/src/storage.js:99
TypeError: Cannot read property 'on' of undefined

(will continue chipping away at it)